POST http://localhost:3333/users
Content-Type: application/json

{
 "email": "isaacsvianna@gmail.com",
  "password": "123456",
  "role": "ADMIN"
}

###
POST http://localhost:3333/jobs
Content-Type: application/json

{
  "title": "Cuidador de idoso com Alzheimer",
  "description": "Cuidar de idoso com Alzheimer, realizar atividades de lazer, higiene pessoal e alimentação.",
  "salary": 3000,
  "contractType": "CLT",
  "location": "Rio de Janeiro - RJ",
  "user": "5ba865bf-b200-4ac1-8dd6-cf8f76a5e0f6"
}

###
GET http://localhost:3333/users/5ba865bf-b200-4ac1-8dd6-cf8f76a5e0f6

###
GET http://localhost:3333/jobs/2
